server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=railway_danang1;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

app:
  jwt:
    secret: RailwayDaNangSecretKeyForJWTTokenGeneration2026VeryLongSecureKey123456789
    expiration-ms: 86400000

  cors:
    allowed-origins: http://localhost:5173
